hydra:
  job:
    chdir: false
batch_size: 6
rand_seed: 1
model_name: model/Mixtral-8x7B-Instruct-v0.1
dpp_sampling: false
scale_factor: null
rerank: false
window: 6
num_candidates: 5
num_ice: 5
output_file: 'output/retrived_data/${task_name}/rerank_${method}_llama2.json'
task_name: scicite
cuda_device: cuda
method: 'mdl'  # mdl/entropy
force_topk: true
instruction_template: 1
span: true
n_tokens: 700
sort: false
use_rand_pool: false
calibrate: false
prior_no: 1
overwrite: true
all_permutation: false
dataset_reader:
  _target_: src.dataset_readers.retriever_dsr.RetrieverDatasetReader
  dataset_path: output/retrived_data/${task_name}/retrieved_topk.json
  task_name: ${task_name}
  model_name: ${model_name}
  index_split: "train"
  n_tokens: 700
  index_data_path: null
model:
  _target_: transformers.AutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: ${model_name}
